name: hello-world

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
            - name: Checkout repository
              repository: RCFixer/hexlet-my-first-workflow
              with:
                  ref: main
            - name: Run make say-hello
              run: make say-hello