name: hello-world

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v3
            repository: RCFixer/hexlet-my-first-workflow
            - run: make say-hello
